### ISSUE TITLE
impurge not working successfully for any input expect already perfect links

### ISSUE THREAD

**Issue by thatchej** [hortinstein/impurge#8]
Hey there, I'm using your library as such:

   ```
function myFunc(link) {
     if(link.indexOf("imgur") > -1) {
                impurge.purge(link, function(e,r) {
                      fixed_link = r;
                });
                return fixed_link;
    }
}
```

In this scenario, `console.log(myFunc('http://imgur.com/a/W8DRd'))` is simply outputting `undefined`. Any known issues going on right now?

**Comment by hortinstein** [comment]
when i run that code, it doesnt like it because you dont define ```fixed_link``` what are you trying to do with the myFunc? ...```impurge``` is purely for spitting out direct links to all images in that album.  and impurge is an async function.  It works like this:

```js

var impurge = require('../impurge.js');

impurge.purge('http://imgur.com/a/W8DRd',function(e,r){
    console.log(r)
})
```
